/* Municipios de Colombia (fuente: DANE) con su zona de envío.
   z: metro=Área Metro Medellín (domiciliario propio) · regional=Antioquia+Eje Cafetero ·
   metropolitano=capitales/ciudades principales · municipal=resto de municipios.
   Tarifa final = matriz categoría × tamaño (1kg/2kg) en app.js (ENVIO_TARIFAS).
   Generado automáticamente — no editar a mano. */
const CIUDADES_CO = [
{n:"Abejorral",d:"Antioquia",z:"regional"},
{n:"Ábrego",d:"Norte de Santander",z:"municipal"},
{n:"Abriaquí",d:"Antioquia",z:"regional"},
{n:"Acacías",d:"Meta",z:"municipal"},
{n:"Acandí",d:"Chocó",z:"municipal"},
{n:"Acevedo",d:"Huila",z:"municipal"},
{n:"Achí",d:"Bolívar",z:"municipal"},
{n:"Agrado",d:"Huila",z:"municipal"},
{n:"Agua de Dios",d:"Cundinamarca",z:"municipal"},
{n:"Aguachica",d:"Cesar",z:"municipal"},
{n:"Aguada",d:"Santander",z:"municipal"},
{n:"Aguadas",d:"Caldas",z:"regional"},
{n:"Aguazul",d:"Casanare",z:"municipal"},
{n:"Agustín Codazzi",d:"Cesar",z:"municipal"},
{n:"Aipe",d:"Huila",z:"municipal"},
{n:"Albán",d:"Cundinamarca",z:"municipal"},
{n:"Albania",d:"Caquetá",z:"municipal"},
{n:"Albania",d:"La Guajira",z:"municipal"},
{n:"Albania",d:"Santander",z:"municipal"},
{n:"Alcalá",d:"Valle del Cauca",z:"municipal"},
{n:"Aldana",d:"Nariño",z:"municipal"},
{n:"Alejandría",d:"Antioquia",z:"regional"},
{n:"Algarrobo",d:"Magdalena",z:"municipal"},
{n:"Algeciras",d:"Huila",z:"municipal"},
{n:"Almaguer",d:"Cauca",z:"municipal"},
{n:"Almeida",d:"Boyacá",z:"municipal"},
{n:"Alpujarra",d:"Tolima",z:"municipal"},
{n:"Altamira",d:"Huila",z:"municipal"},
{n:"Alto Baudó",d:"Chocó",z:"municipal"},
{n:"Altos del Rosario",d:"Bolívar",z:"municipal"},
{n:"Alvarado",d:"Tolima",z:"municipal"},
{n:"Amagá",d:"Antioquia",z:"regional"},
{n:"Amalfi",d:"Antioquia",z:"regional"},
{n:"Ambalema",d:"Tolima",z:"municipal"},
{n:"Anapoima",d:"Cundinamarca",z:"municipal"},
{n:"Ancuyá",d:"Nariño",z:"municipal"},
{n:"Andalucía",d:"Valle del Cauca",z:"municipal"},
{n:"Andes",d:"Antioquia",z:"regional"},
{n:"Angelópolis",d:"Antioquia",z:"regional"},
{n:"Angostura",d:"Antioquia",z:"regional"},
{n:"Anolaima",d:"Cundinamarca",z:"municipal"},
{n:"Anorí",d:"Antioquia",z:"regional"},
{n:"Anserma",d:"Caldas",z:"regional"},
{n:"Ansermanuevo",d:"Valle del Cauca",z:"municipal"},
{n:"Anzá",d:"Antioquia",z:"regional"},
{n:"Anzoátegui",d:"Tolima",z:"municipal"},
{n:"Apartadó",d:"Antioquia",z:"regional"},
{n:"Apía",d:"Risaralda",z:"regional"},
{n:"Apulo",d:"Cundinamarca",z:"municipal"},
{n:"Aquitania",d:"Boyacá",z:"municipal"},
{n:"Aracataca",d:"Magdalena",z:"municipal"},
{n:"Aranzazu",d:"Caldas",z:"regional"},
{n:"Aratoca",d:"Santander",z:"municipal"},
{n:"Arauca",d:"Arauca",z:"metropolitano"},
{n:"Arauquita",d:"Arauca",z:"municipal"},
{n:"Arbeláez",d:"Cundinamarca",z:"municipal"},
{n:"Arboleda",d:"Nariño",z:"municipal"},
{n:"Arboledas",d:"Norte de Santander",z:"municipal"},
{n:"Arboletes",d:"Antioquia",z:"regional"},
{n:"Arcabuco",d:"Boyacá",z:"municipal"},
{n:"Arenal",d:"Bolívar",z:"municipal"},
{n:"Argelia",d:"Antioquia",z:"regional"},
{n:"Argelia",d:"Cauca",z:"municipal"},
{n:"Argelia",d:"Valle del Cauca",z:"municipal"},
{n:"Ariguaní",d:"Magdalena",z:"municipal"},
{n:"Arjona",d:"Bolívar",z:"municipal"},
{n:"Armenia",d:"Antioquia",z:"regional"},
{n:"Armenia",d:"Quindío",z:"regional"},
{n:"Armero",d:"Tolima",z:"municipal"},
{n:"Arroyohondo",d:"Bolívar",z:"municipal"},
{n:"Astrea",d:"Cesar",z:"municipal"},
{n:"Ataco",d:"Tolima",z:"municipal"},
{n:"Ayapel",d:"Córdoba",z:"municipal"},
{n:"Bagadó",d:"Chocó",z:"municipal"},
{n:"Bahía Solano",d:"Chocó",z:"municipal"},
{n:"Bajo Baudó",d:"Chocó",z:"municipal"},
{n:"Balboa",d:"Cauca",z:"municipal"},
{n:"Balboa",d:"Risaralda",z:"regional"},
{n:"Baranoa",d:"Atlántico",z:"municipal"},
{n:"Baraya",d:"Huila",z:"municipal"},
{n:"Barbacoas",d:"Nariño",z:"municipal"},
{n:"Barbosa",d:"Antioquia",z:"metro"},
{n:"Barbosa",d:"Santander",z:"municipal"},
{n:"Barichara",d:"Santander",z:"municipal"},
{n:"Barranca de Upía",d:"Meta",z:"municipal"},
{n:"Barrancabermeja",d:"Santander",z:"municipal"},
{n:"Barrancas",d:"La Guajira",z:"municipal"},
{n:"Barranco de Loba",d:"Bolívar",z:"municipal"},
{n:"Barranquilla",d:"Atlántico",z:"metropolitano"},
{n:"Becerril",d:"Cesar",z:"municipal"},
{n:"Belalcázar",d:"Caldas",z:"regional"},
{n:"Belén",d:"Boyacá",z:"municipal"},
{n:"Belén",d:"Nariño",z:"municipal"},
{n:"Belén de los Andaquíes",d:"Caquetá",z:"municipal"},
{n:"Belén de Umbría",d:"Risaralda",z:"regional"},
{n:"Bello",d:"Antioquia",z:"metro"},
{n:"Belmira",d:"Antioquia",z:"regional"},
{n:"Beltrán",d:"Cundinamarca",z:"municipal"},
{n:"Berbeo",d:"Boyacá",z:"municipal"},
{n:"Betania",d:"Antioquia",z:"regional"},
{n:"Betéitiva",d:"Boyacá",z:"municipal"},
{n:"Betulia",d:"Antioquia",z:"regional"},
{n:"Betulia",d:"Santander",z:"municipal"},
{n:"Bituima",d:"Cundinamarca",z:"municipal"},
{n:"Boavita",d:"Boyacá",z:"municipal"},
{n:"Bochalema",d:"Norte de Santander",z:"municipal"},
{n:"Bogotá",d:"Cundinamarca",z:"metropolitano"},
{n:"Bojacá",d:"Cundinamarca",z:"municipal"},
{n:"Bojayá",d:"Chocó",z:"municipal"},
{n:"Bolívar",d:"Cauca",z:"municipal"},
{n:"Bolívar",d:"Santander",z:"municipal"},
{n:"Bolívar",d:"Valle del Cauca",z:"municipal"},
{n:"Bosconia",d:"Cesar",z:"municipal"},
{n:"Boyacá",d:"Boyacá",z:"municipal"},
{n:"Brazuelo de Papayal",d:"Bolívar",z:"municipal"},
{n:"Briceño",d:"Antioquia",z:"regional"},
{n:"Briceño",d:"Boyacá",z:"municipal"},
{n:"Bucaramanga",d:"Santander",z:"metropolitano"},
{n:"Bucarasica",d:"Norte de Santander",z:"municipal"},
{n:"Buenaventura",d:"Valle del Cauca",z:"municipal"},
{n:"Buenavista",d:"Boyacá",z:"municipal"},
{n:"Buenavista",d:"Córdoba",z:"municipal"},
{n:"Buenavista",d:"Quindío",z:"regional"},
{n:"Buenavista",d:"Sucre",z:"municipal"},
{n:"Buenos Aires",d:"Cauca",z:"municipal"},
{n:"Buesaco",d:"Nariño",z:"municipal"},
{n:"Buga",d:"Valle del Cauca",z:"municipal"},
{n:"Bugalagrande",d:"Valle del Cauca",z:"municipal"},
{n:"Buriticá",d:"Antioquia",z:"regional"},
{n:"Busbanzá",d:"Boyacá",z:"municipal"},
{n:"Cabrera",d:"Cundinamarca",z:"municipal"},
{n:"Cabrera",d:"Santander",z:"municipal"},
{n:"Cabuyaro",d:"Meta",z:"municipal"},
{n:"Cáceres",d:"Antioquia",z:"regional"},
{n:"Cachipay",d:"Cundinamarca",z:"municipal"},
{n:"Cáchira",d:"Norte de Santander",z:"municipal"},
{n:"Cácota",d:"Norte de Santander",z:"municipal"},
{n:"Caicedo",d:"Antioquia",z:"regional"},
{n:"Caicedonia",d:"Valle del Cauca",z:"municipal"},
{n:"Caimito",d:"Sucre",z:"municipal"},
{n:"Cajamarca",d:"Tolima",z:"municipal"},
{n:"Cajibío",d:"Cauca",z:"municipal"},
{n:"Cajicá",d:"Cundinamarca",z:"municipal"},
{n:"Calamar",d:"Bolívar",z:"municipal"},
{n:"Calamar",d:"Guaviare",z:"municipal"},
{n:"Calarcá",d:"Quindío",z:"regional"},
{n:"Caldas",d:"Antioquia",z:"metro"},
{n:"Caldas",d:"Boyacá",z:"municipal"},
{n:"Caldono",d:"Cauca",z:"municipal"},
{n:"Cali",d:"Valle del Cauca",z:"metropolitano"},
{n:"California",d:"Santander",z:"municipal"},
{n:"Calima",d:"Valle del Cauca",z:"municipal"},
{n:"Caloto",d:"Cauca",z:"municipal"},
{n:"Campamento",d:"Antioquia",z:"regional"},
{n:"Campo de la Cruz",d:"Atlántico",z:"municipal"},
{n:"Campoalegre",d:"Huila",z:"municipal"},
{n:"Campohermoso",d:"Boyacá",z:"municipal"},
{n:"Canalete",d:"Córdoba",z:"municipal"},
{n:"Cañasgordas",d:"Antioquia",z:"regional"},
{n:"Candelaria",d:"Atlántico",z:"municipal"},
{n:"Candelaria",d:"Valle del Cauca",z:"municipal"},
{n:"Cantagallo",d:"Bolívar",z:"municipal"},
{n:"Cantón de San Pablo",d:"Chocó",z:"municipal"},
{n:"Caparrapí",d:"Cundinamarca",z:"municipal"},
{n:"Capitanejo",d:"Santander",z:"municipal"},
{n:"Cáqueza",d:"Cundinamarca",z:"municipal"},
{n:"Caracolí",d:"Antioquia",z:"regional"},
{n:"Caramanta",d:"Antioquia",z:"regional"},
{n:"Carcasí",d:"Santander",z:"municipal"},
{n:"Carepa",d:"Antioquia",z:"regional"},
{n:"Carmen de Apicalá",d:"Tolima",z:"municipal"},
{n:"Carmen de Carupa",d:"Cundinamarca",z:"municipal"},
{n:"Carolina del Príncipe",d:"Antioquia",z:"regional"},
{n:"Cartagena de Indias",d:"Bolívar",z:"metropolitano"},
{n:"Cartagena del Chairá",d:"Caquetá",z:"municipal"},
{n:"Cartago",d:"Valle del Cauca",z:"municipal"},
{n:"Carurú",d:"Vaupés",z:"municipal"},
{n:"Casabianca",d:"Tolima",z:"municipal"},
{n:"Castilla la Nueva",d:"Meta",z:"municipal"},
{n:"Caucasia",d:"Antioquia",z:"regional"},
{n:"Cepitá",d:"Santander",z:"municipal"},
{n:"Cereté",d:"Córdoba",z:"municipal"},
{n:"Cerinza",d:"Boyacá",z:"municipal"},
{n:"Cerrito",d:"Santander",z:"municipal"},
{n:"Cerro de San Antonio",d:"Magdalena",z:"municipal"},
{n:"Cértegui",d:"Chocó",z:"municipal"},
{n:"Chachagüí",d:"Nariño",z:"municipal"},
{n:"Chaguaní",d:"Cundinamarca",z:"municipal"},
{n:"Chalán",d:"Sucre",z:"municipal"},
{n:"Chámeza",d:"Casanare",z:"municipal"},
{n:"Chaparral",d:"Tolima",z:"municipal"},
{n:"Charalá",d:"Santander",z:"municipal"},
{n:"Charta",d:"Santander",z:"municipal"},
{n:"Chía",d:"Cundinamarca",z:"municipal"},
{n:"Chibolo",d:"Magdalena",z:"municipal"},
{n:"Chibolo",d:"Magdalena",z:"municipal"},
{n:"Chigorodó",d:"Antioquia",z:"regional"},
{n:"Chimá",d:"Córdoba",z:"municipal"},
{n:"Chima",d:"Santander",z:"municipal"},
{n:"Chimichagua",d:"Cesar",z:"municipal"},
{n:"Chinácota",d:"Norte de Santander",z:"municipal"},
{n:"Chinavita",d:"Boyacá",z:"municipal"},
{n:"Chinchiná",d:"Caldas",z:"regional"},
{n:"Chinú",d:"Córdoba",z:"municipal"},
{n:"Chipaque",d:"Cundinamarca",z:"municipal"},
{n:"Chipatá",d:"Santander",z:"municipal"},
{n:"Chiquinquirá",d:"Boyacá",z:"municipal"},
{n:"Chíquiza",d:"Boyacá",z:"municipal"},
{n:"Chiriguaná",d:"Cesar",z:"municipal"},
{n:"Chiscas",d:"Boyacá",z:"municipal"},
{n:"Chita",d:"Boyacá",z:"municipal"},
{n:"Chitagá",d:"Norte de Santander",z:"municipal"},
{n:"Chitaraque",d:"Boyacá",z:"municipal"},
{n:"Chivatá",d:"Boyacá",z:"municipal"},
{n:"Chivor",d:"Boyacá",z:"municipal"},
{n:"Choachí",d:"Cundinamarca",z:"municipal"},
{n:"Chocontá",d:"Cundinamarca",z:"municipal"},
{n:"Cicuco",d:"Bolívar",z:"municipal"},
{n:"Ciénaga",d:"Magdalena",z:"municipal"},
{n:"Ciénaga de Oro",d:"Córdoba",z:"municipal"},
{n:"Ciénega",d:"Boyacá",z:"municipal"},
{n:"Cimitarra",d:"Santander",z:"municipal"},
{n:"Circasia",d:"Quindío",z:"regional"},
{n:"Cisneros",d:"Antioquia",z:"regional"},
{n:"Ciudad Bolívar",d:"Antioquia",z:"regional"},
{n:"Clemencia",d:"Bolívar",z:"municipal"},
{n:"Cocorná",d:"Antioquia",z:"regional"},
{n:"Coello",d:"Tolima",z:"municipal"},
{n:"Cogua",d:"Cundinamarca",z:"municipal"},
{n:"Colombia",d:"Huila",z:"municipal"},
{n:"Colón",d:"Nariño",z:"municipal"},
{n:"Colón",d:"Putumayo",z:"municipal"},
{n:"Colosó",d:"Sucre",z:"municipal"},
{n:"Cómbita",d:"Boyacá",z:"municipal"},
{n:"Concepción",d:"Antioquia",z:"regional"},
{n:"Concepción",d:"Santander",z:"municipal"},
{n:"Concordia",d:"Antioquia",z:"regional"},
{n:"Concordia",d:"Magdalena",z:"municipal"},
{n:"Condoto",d:"Chocó",z:"municipal"},
{n:"Confines",d:"Santander",z:"municipal"},
{n:"Consacá",d:"Nariño",z:"municipal"},
{n:"Contadero",d:"Nariño",z:"municipal"},
{n:"Contratación",d:"Santander",z:"municipal"},
{n:"Convención",d:"Norte de Santander",z:"municipal"},
{n:"Copacabana",d:"Antioquia",z:"metro"},
{n:"Coper",d:"Boyacá",z:"municipal"},
{n:"Córdoba",d:"Bolívar",z:"municipal"},
{n:"Córdoba",d:"Nariño",z:"municipal"},
{n:"Córdoba",d:"Quindío",z:"regional"},
{n:"Corinto",d:"Cauca",z:"municipal"},
{n:"Coromoro",d:"Santander",z:"municipal"},
{n:"Corozal",d:"Sucre",z:"municipal"},
{n:"Corrales",d:"Boyacá",z:"municipal"},
{n:"Cota",d:"Cundinamarca",z:"municipal"},
{n:"Cotorra",d:"Córdoba",z:"municipal"},
{n:"Covarachía",d:"Boyacá",z:"municipal"},
{n:"Coveñas",d:"Sucre",z:"municipal"},
{n:"Coyaima",d:"Tolima",z:"municipal"},
{n:"Cravo Norte",d:"Arauca",z:"municipal"},
{n:"Cuaspud",d:"Nariño",z:"municipal"},
{n:"Cubará",d:"Boyacá",z:"municipal"},
{n:"Cubarral",d:"Meta",z:"municipal"},
{n:"Cucaita",d:"Boyacá",z:"municipal"},
{n:"Cucunubá",d:"Cundinamarca",z:"municipal"},
{n:"Cúcuta",d:"Norte de Santander",z:"metropolitano"},
{n:"Cucutilla",d:"Norte de Santander",z:"municipal"},
{n:"Cuítiva",d:"Boyacá",z:"municipal"},
{n:"Cumaral",d:"Meta",z:"municipal"},
{n:"Cumaribo",d:"Vichada",z:"municipal"},
{n:"Cumbal",d:"Nariño",z:"municipal"},
{n:"Cumbitara",d:"Nariño",z:"municipal"},
{n:"Cunday",d:"Tolima",z:"municipal"},
{n:"Curillo",d:"Caquetá",z:"municipal"},
{n:"Curití",d:"Santander",z:"municipal"},
{n:"Curumaní",d:"Cesar",z:"municipal"},
{n:"Dabeiba",d:"Antioquia",z:"regional"},
{n:"Dagua",d:"Valle del Cauca",z:"municipal"},
{n:"Dibulla",d:"La Guajira",z:"municipal"},
{n:"Distracción",d:"La Guajira",z:"municipal"},
{n:"Dolores",d:"Tolima",z:"municipal"},
{n:"Donmatías",d:"Antioquia",z:"regional"},
{n:"Dosquebradas",d:"Risaralda",z:"regional"},
{n:"Duitama",d:"Boyacá",z:"municipal"},
{n:"Duranía",d:"Norte de Santander",z:"municipal"},
{n:"Ebéjico",d:"Antioquia",z:"regional"},
{n:"El Águila",d:"Valle del Cauca",z:"municipal"},
{n:"El Atrato",d:"Chocó",z:"municipal"},
{n:"El Bagre",d:"Antioquia",z:"regional"},
{n:"El Banco",d:"Magdalena",z:"municipal"},
{n:"El Cairo",d:"Valle del Cauca",z:"municipal"},
{n:"El Calvario",d:"Meta",z:"municipal"},
{n:"El Carmen",d:"Norte de Santander",z:"municipal"},
{n:"El Carmen de Atrato",d:"Chocó",z:"municipal"},
{n:"El Carmen de Bolívar",d:"Bolívar",z:"municipal"},
{n:"El Carmen de Chucurí",d:"Santander",z:"municipal"},
{n:"El Carmen de Viboral",d:"Antioquia",z:"regional"},
{n:"El Carmen del Darién",d:"Chocó",z:"municipal"},
{n:"El Castillo",d:"Meta",z:"municipal"},
{n:"El Cerrito",d:"Valle del Cauca",z:"municipal"},
{n:"El Charco",d:"Nariño",z:"municipal"},
{n:"El Cocuy",d:"Boyacá",z:"municipal"},
{n:"El Colegio",d:"Cundinamarca",z:"municipal"},
{n:"El Copey",d:"Cesar",z:"municipal"},
{n:"El Doncello",d:"Caquetá",z:"municipal"},
{n:"El Dorado",d:"Meta",z:"municipal"},
{n:"El Dovio",d:"Valle del Cauca",z:"municipal"},
{n:"El Espinal",d:"Tolima",z:"municipal"},
{n:"El Espino",d:"Boyacá",z:"municipal"},
{n:"El Guacamayo",d:"Santander",z:"municipal"},
{n:"El Guamo",d:"Bolívar",z:"municipal"},
{n:"El Molino",d:"La Guajira",z:"municipal"},
{n:"El Paso",d:"Cesar",z:"municipal"},
{n:"El Paujil",d:"Caquetá",z:"municipal"},
{n:"El Peñol",d:"Antioquia",z:"regional"},
{n:"El Peñol",d:"Nariño",z:"municipal"},
{n:"El Peñón",d:"Bolívar",z:"municipal"},
{n:"El Peñón",d:"Cundinamarca",z:"municipal"},
{n:"El Peñón",d:"Santander",z:"municipal"},
{n:"El Piñón",d:"Magdalena",z:"municipal"},
{n:"El Pital",d:"Huila",z:"municipal"},
{n:"El Playón",d:"Santander",z:"municipal"},
{n:"El Retén",d:"Magdalena",z:"municipal"},
{n:"El Retiro",d:"Antioquia",z:"regional"},
{n:"El Retorno",d:"Guaviare",z:"municipal"},
{n:"El Roble",d:"Sucre",z:"municipal"},
{n:"El Rosal",d:"Cundinamarca",z:"municipal"},
{n:"El Rosario",d:"Nariño",z:"municipal"},
{n:"El Santuario",d:"Antioquia",z:"regional"},
{n:"El Socorro",d:"Santander",z:"municipal"},
{n:"El Tablón",d:"Nariño",z:"municipal"},
{n:"El Tambo",d:"Cauca",z:"municipal"},
{n:"El Tambo",d:"Nariño",z:"municipal"},
{n:"El Tarra",d:"Norte de Santander",z:"municipal"},
{n:"El Zulia",d:"Norte de Santander",z:"municipal"},
{n:"Elías",d:"Huila",z:"municipal"},
{n:"Encino",d:"Santander",z:"municipal"},
{n:"Enciso",d:"Santander",z:"municipal"},
{n:"Entrerríos",d:"Antioquia",z:"regional"},
{n:"Envigado",d:"Antioquia",z:"metro"},
{n:"Facatativá",d:"Cundinamarca",z:"municipal"},
{n:"Falán",d:"Tolima",z:"municipal"},
{n:"Filadelfia",d:"Caldas",z:"regional"},
{n:"Filandia",d:"Quindío",z:"regional"},
{n:"Firavitoba",d:"Boyacá",z:"municipal"},
{n:"Flandes",d:"Tolima",z:"municipal"},
{n:"Florencia",d:"Caquetá",z:"metropolitano"},
{n:"Florencia",d:"Cauca",z:"municipal"},
{n:"Floresta",d:"Boyacá",z:"municipal"},
{n:"Florián",d:"Santander",z:"municipal"},
{n:"Florida",d:"Valle del Cauca",z:"municipal"},
{n:"Floridablanca",d:"Santander",z:"metropolitano"},
{n:"Fómeque",d:"Cundinamarca",z:"municipal"},
{n:"Fonseca",d:"La Guajira",z:"municipal"},
{n:"Fortul",d:"Arauca",z:"municipal"},
{n:"Fosca",d:"Cundinamarca",z:"municipal"},
{n:"Francisco Pizarro",d:"Nariño",z:"municipal"},
{n:"Fredonia",d:"Antioquia",z:"regional"},
{n:"Fresno",d:"Tolima",z:"municipal"},
{n:"Frontino",d:"Antioquia",z:"regional"},
{n:"Fuente de Oro",d:"Meta",z:"municipal"},
{n:"Fundación",d:"Magdalena",z:"municipal"},
{n:"Funes",d:"Nariño",z:"municipal"},
{n:"Funza",d:"Cundinamarca",z:"municipal"},
{n:"Fúquene",d:"Cundinamarca",z:"municipal"},
{n:"Fusagasugá",d:"Cundinamarca",z:"municipal"},
{n:"Gachalá",d:"Cundinamarca",z:"municipal"},
{n:"Gachancipá",d:"Cundinamarca",z:"municipal"},
{n:"Gachantivá",d:"Boyacá",z:"municipal"},
{n:"Gachetá",d:"Cundinamarca",z:"municipal"},
{n:"Galán",d:"Santander",z:"municipal"},
{n:"Galapa",d:"Atlántico",z:"municipal"},
{n:"Galeras",d:"Sucre",z:"municipal"},
{n:"Gama",d:"Cundinamarca",z:"municipal"},
{n:"Gamarra",d:"Cesar",z:"municipal"},
{n:"Gámbita",d:"Santander",z:"municipal"},
{n:"Gámeza",d:"Boyacá",z:"municipal"},
{n:"Garagoa",d:"Boyacá",z:"municipal"},
{n:"Garzón",d:"Huila",z:"municipal"},
{n:"Génova",d:"Quindío",z:"regional"},
{n:"Gigante",d:"Huila",z:"municipal"},
{n:"Ginebra",d:"Valle del Cauca",z:"municipal"},
{n:"Giraldo",d:"Antioquia",z:"regional"},
{n:"Girardot",d:"Cundinamarca",z:"municipal"},
{n:"Girardota",d:"Antioquia",z:"metro"},
{n:"Girón",d:"Santander",z:"metropolitano"},
{n:"Gómez Plata",d:"Antioquia",z:"regional"},
{n:"González",d:"Cesar",z:"municipal"},
{n:"Gramalote",d:"Norte de Santander",z:"municipal"},
{n:"Granada",d:"Antioquia",z:"regional"},
{n:"Granada",d:"Cundinamarca",z:"municipal"},
{n:"Granada",d:"Meta",z:"municipal"},
{n:"Guaca",d:"Santander",z:"municipal"},
{n:"Guacamayas",d:"Boyacá",z:"municipal"},
{n:"Guacarí",d:"Valle del Cauca",z:"municipal"},
{n:"Guachené",d:"Cauca",z:"municipal"},
{n:"Guachetá",d:"Cundinamarca",z:"municipal"},
{n:"Guachucal",d:"Nariño",z:"municipal"},
{n:"Guadalupe",d:"Antioquia",z:"regional"},
{n:"Guadalupe",d:"Huila",z:"municipal"},
{n:"Guadalupe",d:"Santander",z:"municipal"},
{n:"Guaduas",d:"Cundinamarca",z:"municipal"},
{n:"Guaitarilla",d:"Nariño",z:"municipal"},
{n:"Gualmatán",d:"Nariño",z:"municipal"},
{n:"Guamal",d:"Magdalena",z:"municipal"},
{n:"Guamal",d:"Meta",z:"municipal"},
{n:"Guamo",d:"Tolima",z:"municipal"},
{n:"Guapí",d:"Cauca",z:"municipal"},
{n:"Guapotá",d:"Santander",z:"municipal"},
{n:"Guaranda",d:"Sucre",z:"municipal"},
{n:"Guarne",d:"Antioquia",z:"regional"},
{n:"Guasca",d:"Cundinamarca",z:"municipal"},
{n:"Guatapé",d:"Antioquia",z:"regional"},
{n:"Guataquí",d:"Cundinamarca",z:"municipal"},
{n:"Guatavita",d:"Cundinamarca",z:"municipal"},
{n:"Guateque",d:"Boyacá",z:"municipal"},
{n:"Guática",d:"Risaralda",z:"regional"},
{n:"Guavatá",d:"Santander",z:"municipal"},
{n:"Guayabal de Síquima",d:"Cundinamarca",z:"municipal"},
{n:"Guayabetal",d:"Cundinamarca",z:"municipal"},
{n:"Guayatá",d:"Boyacá",z:"municipal"},
{n:"Güepsa",d:"Santander",z:"municipal"},
{n:"Güicán",d:"Boyacá",z:"municipal"},
{n:"Gutiérrez",d:"Cundinamarca",z:"municipal"},
{n:"Hacarí",d:"Norte de Santander",z:"municipal"},
{n:"Hatillo de Loba",d:"Bolívar",z:"municipal"},
{n:"Hato",d:"Santander",z:"municipal"},
{n:"Hato Corozal",d:"Casanare",z:"municipal"},
{n:"Hatonuevo",d:"La Guajira",z:"municipal"},
{n:"Heliconia",d:"Antioquia",z:"regional"},
{n:"Herrán",d:"Norte de Santander",z:"municipal"},
{n:"Herveo",d:"Tolima",z:"municipal"},
{n:"Hispania",d:"Antioquia",z:"regional"},
{n:"Hobo",d:"Huila",z:"municipal"},
{n:"Honda",d:"Tolima",z:"municipal"},
{n:"Ibagué",d:"Tolima",z:"metropolitano"},
{n:"Icononzo",d:"Tolima",z:"municipal"},
{n:"Iles",d:"Nariño",z:"municipal"},
{n:"Imués",d:"Nariño",z:"municipal"},
{n:"Inírida",d:"Guainía",z:"municipal"},
{n:"Inzá",d:"Cauca",z:"municipal"},
{n:"Ipiales",d:"Nariño",z:"municipal"},
{n:"Íquira",d:"Huila",z:"municipal"},
{n:"Isnos",d:"Huila",z:"municipal"},
{n:"Istmina",d:"Chocó",z:"municipal"},
{n:"Itagüí",d:"Antioquia",z:"metro"},
{n:"Ituango",d:"Antioquia",z:"regional"},
{n:"Iza",d:"Boyacá",z:"municipal"},
{n:"Jambaló",d:"Cauca",z:"municipal"},
{n:"Jamundí",d:"Valle del Cauca",z:"metropolitano"},
{n:"Jardín",d:"Antioquia",z:"regional"},
{n:"Jenesano",d:"Boyacá",z:"municipal"},
{n:"Jericó",d:"Antioquia",z:"regional"},
{n:"Jericó",d:"Boyacá",z:"municipal"},
{n:"Jerusalén",d:"Cundinamarca",z:"municipal"},
{n:"Jesús María",d:"Santander",z:"municipal"},
{n:"Jordán",d:"Santander",z:"municipal"},
{n:"Juan de Acosta",d:"Atlántico",z:"municipal"},
{n:"Junín",d:"Cundinamarca",z:"municipal"},
{n:"Juradó",d:"Chocó",z:"municipal"},
{n:"La Apartada",d:"Córdoba",z:"municipal"},
{n:"La Argentina",d:"Huila",z:"municipal"},
{n:"La Belleza",d:"Santander",z:"municipal"},
{n:"La Calera",d:"Cundinamarca",z:"municipal"},
{n:"La Capilla",d:"Boyacá",z:"municipal"},
{n:"La Ceja",d:"Antioquia",z:"regional"},
{n:"La Celia",d:"Risaralda",z:"regional"},
{n:"La Cruz",d:"Nariño",z:"municipal"},
{n:"La Cumbre",d:"Valle del Cauca",z:"municipal"},
{n:"La Dorada",d:"Caldas",z:"regional"},
{n:"La Esperanza",d:"Norte de Santander",z:"municipal"},
{n:"La Estrella",d:"Antioquia",z:"metro"},
{n:"La Florida",d:"Nariño",z:"municipal"},
{n:"La Gloria (Cesar)",d:"Cesar",z:"municipal"},
{n:"La Jagua de Ibirico",d:"Cesar",z:"municipal"},
{n:"La Jagua del Pilar",d:"La Guajira",z:"municipal"},
{n:"La Llanada",d:"Nariño",z:"municipal"},
{n:"La Macarena",d:"Meta",z:"municipal"},
{n:"La Merced",d:"Caldas",z:"regional"},
{n:"La Mesa",d:"Cundinamarca",z:"municipal"},
{n:"La Montañita",d:"Caquetá",z:"municipal"},
{n:"La Palma",d:"Cundinamarca",z:"municipal"},
{n:"La Paz",d:"Cesar",z:"municipal"},
{n:"La Paz",d:"Santander",z:"municipal"},
{n:"La Peña",d:"Cundinamarca",z:"municipal"},
{n:"La Pintada",d:"Antioquia",z:"regional"},
{n:"La Plata",d:"Huila",z:"municipal"},
{n:"La Playa de Belén",d:"Norte de Santander",z:"municipal"},
{n:"La Primavera",d:"Vichada",z:"municipal"},
{n:"La Salina",d:"Casanare",z:"municipal"},
{n:"La Sierra",d:"Cauca",z:"municipal"},
{n:"La Tebaida",d:"Quindío",z:"regional"},
{n:"La Tola",d:"Nariño",z:"municipal"},
{n:"La Unión",d:"Antioquia",z:"regional"},
{n:"La Unión",d:"Nariño",z:"municipal"},
{n:"La Unión",d:"Sucre",z:"municipal"},
{n:"La Unión",d:"Valle del Cauca",z:"municipal"},
{n:"La Uribe",d:"Meta",z:"municipal"},
{n:"La Uvita",d:"Boyacá",z:"municipal"},
{n:"La Vega",d:"Cauca",z:"municipal"},
{n:"La Vega",d:"Cundinamarca",z:"municipal"},
{n:"La Victoria",d:"Boyacá",z:"municipal"},
{n:"La Victoria",d:"Valle del Cauca",z:"municipal"},
{n:"La Virginia",d:"Risaralda",z:"regional"},
{n:"Labateca",d:"Norte de Santander",z:"municipal"},
{n:"Labranzagrande",d:"Boyacá",z:"municipal"},
{n:"Landázuri",d:"Santander",z:"municipal"},
{n:"Lebrija",d:"Santander",z:"municipal"},
{n:"Leiva",d:"Nariño",z:"municipal"},
{n:"Lejanías",d:"Meta",z:"municipal"},
{n:"Lenguazaque",d:"Cundinamarca",z:"municipal"},
{n:"Lérida",d:"Tolima",z:"municipal"},
{n:"Leticia",d:"Amazonas",z:"municipal"},
{n:"Líbano",d:"Tolima",z:"municipal"},
{n:"Liborina",d:"Antioquia",z:"regional"},
{n:"Linares",d:"Nariño",z:"municipal"},
{n:"Litoral de San Juan",d:"Chocó",z:"municipal"},
{n:"Lloró",d:"Chocó",z:"municipal"},
{n:"López de Micay",d:"Cauca",z:"municipal"},
{n:"Lorica",d:"Córdoba",z:"municipal"},
{n:"Los Andes",d:"Nariño",z:"municipal"},
{n:"Los Córdobas",d:"Córdoba",z:"municipal"},
{n:"Los Palmitos",d:"Sucre",z:"municipal"},
{n:"Los Patios",d:"Norte de Santander",z:"municipal"},
{n:"Los Santos",d:"Santander",z:"municipal"},
{n:"Lourdes",d:"Norte de Santander",z:"municipal"},
{n:"Luruaco",d:"Atlántico",z:"municipal"},
{n:"Macanal",d:"Boyacá",z:"municipal"},
{n:"Macaravita",d:"Santander",z:"municipal"},
{n:"Maceo",d:"Antioquia",z:"regional"},
{n:"Machetá",d:"Cundinamarca",z:"municipal"},
{n:"Madrid",d:"Cundinamarca",z:"municipal"},
{n:"Magangué",d:"Bolívar",z:"municipal"},
{n:"Magüí Payán",d:"Nariño",z:"municipal"},
{n:"Mahates",d:"Bolívar",z:"municipal"},
{n:"Maicao",d:"La Guajira",z:"municipal"},
{n:"Majagual",d:"Sucre",z:"municipal"},
{n:"Málaga",d:"Santander",z:"municipal"},
{n:"Malambo",d:"Atlántico",z:"metropolitano"},
{n:"Mallama",d:"Nariño",z:"municipal"},
{n:"Manatí",d:"Atlántico",z:"municipal"},
{n:"Manaure",d:"La Guajira",z:"municipal"},
{n:"Manaure Balcón del Cesar",d:"Cesar",z:"municipal"},
{n:"Maní",d:"Casanare",z:"municipal"},
{n:"Manizales",d:"Caldas",z:"regional"},
{n:"Manta",d:"Cundinamarca",z:"municipal"},
{n:"Manzanares",d:"Caldas",z:"regional"},
{n:"Mapiripán",d:"Meta",z:"municipal"},
{n:"Margarita",d:"Bolívar",z:"municipal"},
{n:"María la Baja",d:"Bolívar",z:"municipal"},
{n:"Marinilla",d:"Antioquia",z:"regional"},
{n:"Maripí",d:"Boyacá",z:"municipal"},
{n:"Mariquita",d:"Tolima",z:"municipal"},
{n:"Marmato",d:"Caldas",z:"regional"},
{n:"Marquetalia",d:"Caldas",z:"regional"},
{n:"Marsella",d:"Risaralda",z:"regional"},
{n:"Marulanda",d:"Caldas",z:"regional"},
{n:"Matanza",d:"Santander",z:"municipal"},
{n:"Medellín",d:"Antioquia",z:"metro"},
{n:"Medina",d:"Cundinamarca",z:"municipal"},
{n:"Medio Atrato",d:"Chocó",z:"municipal"},
{n:"Medio Baudó",d:"Chocó",z:"municipal"},
{n:"Medio San Juan",d:"Chocó",z:"municipal"},
{n:"Melgar",d:"Tolima",z:"municipal"},
{n:"Mercaderes",d:"Cauca",z:"municipal"},
{n:"Mesetas",d:"Meta",z:"municipal"},
{n:"Milán",d:"Caquetá",z:"municipal"},
{n:"Miraflores",d:"Boyacá",z:"municipal"},
{n:"Miraflores",d:"Guaviare",z:"municipal"},
{n:"Miranda",d:"Cauca",z:"municipal"},
{n:"Mistrató",d:"Risaralda",z:"regional"},
{n:"Mitú",d:"Vaupés",z:"municipal"},
{n:"Mocoa",d:"Putumayo",z:"municipal"},
{n:"Mogotes",d:"Santander",z:"municipal"},
{n:"Molagavita",d:"Santander",z:"municipal"},
{n:"Momil",d:"Córdoba",z:"municipal"},
{n:"Mompós",d:"Bolívar",z:"municipal"},
{n:"Mongua",d:"Boyacá",z:"municipal"},
{n:"Monguí",d:"Boyacá",z:"municipal"},
{n:"Moniquirá",d:"Boyacá",z:"municipal"},
{n:"Moñitos",d:"Córdoba",z:"municipal"},
{n:"Montebello",d:"Antioquia",z:"regional"},
{n:"Montecristo",d:"Bolívar",z:"municipal"},
{n:"Montelíbano",d:"Córdoba",z:"municipal"},
{n:"Montenegro",d:"Quindío",z:"regional"},
{n:"Montería",d:"Córdoba",z:"metropolitano"},
{n:"Monterrey",d:"Casanare",z:"municipal"},
{n:"Morales",d:"Bolívar",z:"municipal"},
{n:"Morales",d:"Cauca",z:"municipal"},
{n:"Morelia",d:"Caquetá",z:"municipal"},
{n:"Morroa",d:"Sucre",z:"municipal"},
{n:"Mosquera",d:"Cundinamarca",z:"municipal"},
{n:"Mosquera",d:"Nariño",z:"municipal"},
{n:"Motavita",d:"Boyacá",z:"municipal"},
{n:"Murillo",d:"Tolima",z:"municipal"},
{n:"Murindó",d:"Antioquia",z:"regional"},
{n:"Mutatá",d:"Antioquia",z:"regional"},
{n:"Mutiscua",d:"Norte de Santander",z:"municipal"},
{n:"Muzo",d:"Boyacá",z:"municipal"},
{n:"Nariño",d:"Antioquia",z:"regional"},
{n:"Nariño",d:"Cundinamarca",z:"municipal"},
{n:"Nariño",d:"Nariño",z:"municipal"},
{n:"Nátaga",d:"Huila",z:"municipal"},
{n:"Natagaima",d:"Tolima",z:"municipal"},
{n:"Nechí",d:"Antioquia",z:"regional"},
{n:"Necoclí",d:"Antioquia",z:"regional"},
{n:"Neira",d:"Caldas",z:"regional"},
{n:"Neiva",d:"Huila",z:"metropolitano"},
{n:"Nemocón",d:"Cundinamarca",z:"municipal"},
{n:"Nilo",d:"Cundinamarca",z:"municipal"},
{n:"Nimaima",d:"Cundinamarca",z:"municipal"},
{n:"Nobsa",d:"Boyacá",z:"municipal"},
{n:"Nocaima",d:"Cundinamarca",z:"municipal"},
{n:"Norcasia",d:"Caldas",z:"regional"},
{n:"Norosí",d:"Bolívar",z:"municipal"},
{n:"Nóvita",d:"Chocó",z:"municipal"},
{n:"Nueva Granada",d:"Magdalena",z:"municipal"},
{n:"Nuevo Colón",d:"Boyacá",z:"municipal"},
{n:"Nunchía",d:"Casanare",z:"municipal"},
{n:"Nuquí",d:"Chocó",z:"municipal"},
{n:"Obando",d:"Valle del Cauca",z:"municipal"},
{n:"Ocamonte",d:"Santander",z:"municipal"},
{n:"Ocaña",d:"Norte de Santander",z:"municipal"},
{n:"Oiba",d:"Santander",z:"municipal"},
{n:"Oicatá",d:"Boyacá",z:"municipal"},
{n:"Olaya",d:"Antioquia",z:"regional"},
{n:"Olaya Herrera",d:"Nariño",z:"municipal"},
{n:"Onzaga",d:"Santander",z:"municipal"},
{n:"Oporapa",d:"Huila",z:"municipal"},
{n:"Orito",d:"Putumayo",z:"municipal"},
{n:"Orocué",d:"Casanare",z:"municipal"},
{n:"Ortega",d:"Tolima",z:"municipal"},
{n:"Ospina",d:"Nariño",z:"municipal"},
{n:"Otanche",d:"Boyacá",z:"municipal"},
{n:"Ovejas",d:"Sucre",z:"municipal"},
{n:"Pachavita",d:"Boyacá",z:"municipal"},
{n:"Pacho",d:"Cundinamarca",z:"municipal"},
{n:"Pácora",d:"Caldas",z:"regional"},
{n:"Padilla",d:"Cauca",z:"municipal"},
{n:"Páez",d:"Boyacá",z:"municipal"},
{n:"Páez",d:"Cauca",z:"municipal"},
{n:"Paicol",d:"Huila",z:"municipal"},
{n:"Pailitas",d:"Cesar",z:"municipal"},
{n:"Paime",d:"Cundinamarca",z:"municipal"},
{n:"Paipa",d:"Boyacá",z:"municipal"},
{n:"Pajarito",d:"Boyacá",z:"municipal"},
{n:"Palermo",d:"Huila",z:"municipal"},
{n:"Palestina",d:"Caldas",z:"regional"},
{n:"Palestina",d:"Huila",z:"municipal"},
{n:"Palmar",d:"Santander",z:"municipal"},
{n:"Palmar de Varela",d:"Atlántico",z:"municipal"},
{n:"Palmas del Socorro",d:"Santander",z:"municipal"},
{n:"Palmira",d:"Valle del Cauca",z:"metropolitano"},
{n:"Palocabildo",d:"Tolima",z:"municipal"},
{n:"Pamplona",d:"Norte de Santander",z:"municipal"},
{n:"Pamplonita",d:"Norte de Santander",z:"municipal"},
{n:"Pandi",d:"Cundinamarca",z:"municipal"},
{n:"Panqueba",d:"Boyacá",z:"municipal"},
{n:"Páramo",d:"Santander",z:"municipal"},
{n:"Paratebueno",d:"Cundinamarca",z:"municipal"},
{n:"Pasca",d:"Cundinamarca",z:"municipal"},
{n:"Pasto",d:"Nariño",z:"metropolitano"},
{n:"Patía",d:"Cauca",z:"municipal"},
{n:"Pauna",d:"Boyacá",z:"municipal"},
{n:"Paya",d:"Boyacá",z:"municipal"},
{n:"Paz de Ariporo",d:"Casanare",z:"municipal"},
{n:"Paz del Río",d:"Boyacá",z:"municipal"},
{n:"Pedraza",d:"Magdalena",z:"municipal"},
{n:"Pelaya",d:"Cesar",z:"municipal"},
{n:"Pensilvania",d:"Caldas",z:"regional"},
{n:"Peque",d:"Antioquia",z:"regional"},
{n:"Pereira",d:"Risaralda",z:"regional"},
{n:"Pesca",d:"Boyacá",z:"municipal"},
{n:"Piamonte",d:"Cauca",z:"municipal"},
{n:"Piedecuesta",d:"Santander",z:"metropolitano"},
{n:"Piedras",d:"Tolima",z:"municipal"},
{n:"Piendamó",d:"Cauca",z:"municipal"},
{n:"Pijao",d:"Quindío",z:"regional"},
{n:"Pijiño del Carmen",d:"Magdalena",z:"municipal"},
{n:"Pinchote",d:"Santander",z:"municipal"},
{n:"Pinillos",d:"Bolívar",z:"municipal"},
{n:"Piojó",d:"Atlántico",z:"municipal"},
{n:"Pisba",d:"Boyacá",z:"municipal"},
{n:"Pitalito",d:"Huila",z:"municipal"},
{n:"Pivijay",d:"Magdalena",z:"municipal"},
{n:"Planadas",d:"Tolima",z:"municipal"},
{n:"Planeta Rica",d:"Córdoba",z:"municipal"},
{n:"Plato",d:"Magdalena",z:"municipal"},
{n:"Policarpa",d:"Nariño",z:"municipal"},
{n:"Polonuevo",d:"Atlántico",z:"municipal"},
{n:"Ponedera",d:"Atlántico",z:"municipal"},
{n:"Popayán",d:"Cauca",z:"metropolitano"},
{n:"Pore",d:"Casanare",z:"municipal"},
{n:"Potosí",d:"Nariño",z:"municipal"},
{n:"Pradera",d:"Valle del Cauca",z:"municipal"},
{n:"Prado",d:"Tolima",z:"municipal"},
{n:"Providencia",d:"Nariño",z:"municipal"},
{n:"Providencia y Santa Catalina Islas",d:"San Andrés y Providencia",z:"municipal"},
{n:"Pueblo Bello",d:"Cesar",z:"municipal"},
{n:"Pueblo Nuevo",d:"Córdoba",z:"municipal"},
{n:"Pueblo Rico",d:"Risaralda",z:"regional"},
{n:"Pueblo Viejo",d:"Magdalena",z:"municipal"},
{n:"Pueblorrico",d:"Antioquia",z:"regional"},
{n:"Puente Nacional",d:"Santander",z:"municipal"},
{n:"Puerres",d:"Nariño",z:"municipal"},
{n:"Puerto Asís",d:"Putumayo",z:"municipal"},
{n:"Puerto Berrío",d:"Antioquia",z:"regional"},
{n:"Puerto Boyacá",d:"Boyacá",z:"municipal"},
{n:"Puerto Caicedo",d:"Putumayo",z:"municipal"},
{n:"Puerto Carreño",d:"Vichada",z:"municipal"},
{n:"Puerto Colombia",d:"Atlántico",z:"municipal"},
{n:"Puerto Concordia",d:"Meta",z:"municipal"},
{n:"Puerto Escondido",d:"Córdoba",z:"municipal"},
{n:"Puerto Gaitán",d:"Meta",z:"municipal"},
{n:"Puerto Guzmán",d:"Putumayo",z:"municipal"},
{n:"Puerto Leguízamo",d:"Putumayo",z:"municipal"},
{n:"Puerto Libertador",d:"Córdoba",z:"municipal"},
{n:"Puerto Lleras",d:"Meta",z:"municipal"},
{n:"Puerto López",d:"Meta",z:"municipal"},
{n:"Puerto Nare",d:"Antioquia",z:"regional"},
{n:"Puerto Nariño",d:"Amazonas",z:"municipal"},
{n:"Puerto Parra",d:"Santander",z:"municipal"},
{n:"Puerto Rico",d:"Caquetá",z:"municipal"},
{n:"Puerto Rico",d:"Meta",z:"municipal"},
{n:"Puerto Rondón",d:"Arauca",z:"municipal"},
{n:"Puerto Salgar",d:"Cundinamarca",z:"municipal"},
{n:"Puerto Santander",d:"Norte de Santander",z:"municipal"},
{n:"Puerto Tejada",d:"Cauca",z:"municipal"},
{n:"Puerto Triunfo",d:"Antioquia",z:"regional"},
{n:"Puerto Wilches",d:"Santander",z:"municipal"},
{n:"Pulí",d:"Cundinamarca",z:"municipal"},
{n:"Pupiales",d:"Nariño",z:"municipal"},
{n:"Puracé",d:"Cauca",z:"municipal"},
{n:"Purificación",d:"Tolima",z:"municipal"},
{n:"Purísima",d:"Córdoba",z:"municipal"},
{n:"Quebradanegra",d:"Cundinamarca",z:"municipal"},
{n:"Quetame",d:"Cundinamarca",z:"municipal"},
{n:"Quibdó",d:"Chocó",z:"metropolitano"},
{n:"Quimbaya",d:"Quindío",z:"regional"},
{n:"Quinchía",d:"Risaralda",z:"regional"},
{n:"Quípama",d:"Boyacá",z:"municipal"},
{n:"Quipile",d:"Cundinamarca",z:"municipal"},
{n:"Ragonvalia",d:"Norte de Santander",z:"municipal"},
{n:"Ramiriquí",d:"Boyacá",z:"municipal"},
{n:"Ráquira",d:"Boyacá",z:"municipal"},
{n:"Recetor",d:"Casanare",z:"municipal"},
{n:"Regidor",d:"Bolívar",z:"municipal"},
{n:"Remedios",d:"Antioquia",z:"regional"},
{n:"Remolino",d:"Magdalena",z:"municipal"},
{n:"Repelón",d:"Atlántico",z:"municipal"},
{n:"Restrepo",d:"Meta",z:"municipal"},
{n:"Restrepo",d:"Valle del Cauca",z:"municipal"},
{n:"Ricaurte",d:"Cundinamarca",z:"municipal"},
{n:"Ricaurte",d:"Nariño",z:"municipal"},
{n:"Río de Oro",d:"Cesar",z:"municipal"},
{n:"Río Iró",d:"Chocó",z:"municipal"},
{n:"Río Quito",d:"Chocó",z:"municipal"},
{n:"Río Viejo",d:"Bolívar",z:"municipal"},
{n:"Rioblanco",d:"Tolima",z:"municipal"},
{n:"Riofrío",d:"Valle del Cauca",z:"municipal"},
{n:"Riohacha",d:"La Guajira",z:"metropolitano"},
{n:"Rionegro",d:"Antioquia",z:"regional"},
{n:"Rionegro",d:"Santander",z:"municipal"},
{n:"Riosucio",d:"Caldas",z:"regional"},
{n:"Riosucio",d:"Chocó",z:"municipal"},
{n:"Risaralda",d:"Caldas",z:"regional"},
{n:"Rivera",d:"Huila",z:"municipal"},
{n:"Roberto Payán",d:"Nariño",z:"municipal"},
{n:"Roldanillo",d:"Valle del Cauca",z:"municipal"},
{n:"Roncesvalles",d:"Tolima",z:"municipal"},
{n:"Rondón",d:"Boyacá",z:"municipal"},
{n:"Rosas",d:"Cauca",z:"municipal"},
{n:"Rovira",d:"Tolima",z:"municipal"},
{n:"Sabana de Torres",d:"Santander",z:"municipal"},
{n:"Sabanagrande",d:"Atlántico",z:"municipal"},
{n:"Sabanalarga",d:"Antioquia",z:"regional"},
{n:"Sabanalarga",d:"Atlántico",z:"municipal"},
{n:"Sabanalarga",d:"Casanare",z:"municipal"},
{n:"Sabanas de San Ángel",d:"Magdalena",z:"municipal"},
{n:"Sabaneta",d:"Antioquia",z:"metro"},
{n:"Saboyá",d:"Boyacá",z:"municipal"},
{n:"Sácama",d:"Casanare",z:"municipal"},
{n:"Sáchica",d:"Boyacá",z:"municipal"},
{n:"Sahagún",d:"Córdoba",z:"municipal"},
{n:"Saladoblanco",d:"Huila",z:"municipal"},
{n:"Salamina",d:"Caldas",z:"regional"},
{n:"Salamina",d:"Magdalena",z:"municipal"},
{n:"Salazar de Las Palmas",d:"Norte de Santander",z:"municipal"},
{n:"Saldaña",d:"Tolima",z:"municipal"},
{n:"Salento",d:"Quindío",z:"regional"},
{n:"Salgar",d:"Antioquia",z:"regional"},
{n:"Samacá",d:"Boyacá",z:"municipal"},
{n:"Samaná",d:"Caldas",z:"regional"},
{n:"Samaniego",d:"Nariño",z:"municipal"},
{n:"Sampués",d:"Sucre",z:"municipal"},
{n:"San Agustín",d:"Huila",z:"municipal"},
{n:"San Alberto",d:"Cesar",z:"municipal"},
{n:"San Andrés",d:"San Andrés y Providencia",z:"municipal"},
{n:"San Andrés",d:"Santander",z:"municipal"},
{n:"San Andrés de Cuerquia",d:"Antioquia",z:"regional"},
{n:"San Andrés de Sotavento",d:"Córdoba",z:"municipal"},
{n:"San Antero",d:"Córdoba",z:"municipal"},
{n:"San Antonio",d:"Tolima",z:"municipal"},
{n:"San Antonio de Palmito",d:"Sucre",z:"municipal"},
{n:"San Antonio del Tequendama",d:"Cundinamarca",z:"municipal"},
{n:"San Benito",d:"Santander",z:"municipal"},
{n:"San Benito Abad",d:"Sucre",z:"municipal"},
{n:"San Bernardo",d:"Cundinamarca",z:"municipal"},
{n:"San Bernardo",d:"Nariño",z:"municipal"},
{n:"San Bernardo del Viento",d:"Córdoba",z:"municipal"},
{n:"San Calixto",d:"Norte de Santander",z:"municipal"},
{n:"San Carlos",d:"Antioquia",z:"regional"},
{n:"San Carlos",d:"Córdoba",z:"municipal"},
{n:"San Carlos de Guaroa",d:"Meta",z:"municipal"},
{n:"San Cayetano",d:"Cundinamarca",z:"municipal"},
{n:"San Cayetano",d:"Norte de Santander",z:"municipal"},
{n:"San Cristóbal",d:"Bolívar",z:"municipal"},
{n:"San Diego",d:"Cesar",z:"municipal"},
{n:"San Eduardo",d:"Boyacá",z:"municipal"},
{n:"San Estanislao",d:"Bolívar",z:"municipal"},
{n:"San Fernando",d:"Bolívar",z:"municipal"},
{n:"San Francisco",d:"Antioquia",z:"regional"},
{n:"San Francisco",d:"Cundinamarca",z:"municipal"},
{n:"San Francisco",d:"Putumayo",z:"municipal"},
{n:"San Gil",d:"Santander",z:"municipal"},
{n:"San Jacinto",d:"Bolívar",z:"municipal"},
{n:"San Jacinto del Cauca",d:"Bolívar",z:"municipal"},
{n:"San Jerónimo",d:"Antioquia",z:"regional"},
{n:"San Joaquín",d:"Santander",z:"municipal"},
{n:"San José",d:"Caldas",z:"regional"},
{n:"San José de Albán",d:"Nariño",z:"municipal"},
{n:"San José de la Montaña",d:"Antioquia",z:"regional"},
{n:"San José de Miranda",d:"Santander",z:"municipal"},
{n:"San José de Pare",d:"Boyacá",z:"municipal"},
{n:"San José de Uré",d:"Córdoba",z:"municipal"},
{n:"San José del Fragua",d:"Caquetá",z:"municipal"},
{n:"San José del Guaviare",d:"Guaviare",z:"municipal"},
{n:"San José del Palmar",d:"Chocó",z:"municipal"},
{n:"San Juan de Arama",d:"Meta",z:"municipal"},
{n:"San Juan de Betulia",d:"Sucre",z:"municipal"},
{n:"San Juan de Rioseco",d:"Cundinamarca",z:"municipal"},
{n:"San Juan de Urabá",d:"Antioquia",z:"regional"},
{n:"San Juan del Cesar",d:"La Guajira",z:"municipal"},
{n:"San Juan Nepomuceno",d:"Bolívar",z:"municipal"},
{n:"San Juanito",d:"Meta",z:"municipal"},
{n:"San Lorenzo",d:"Nariño",z:"municipal"},
{n:"San Luis",d:"Antioquia",z:"regional"},
{n:"San Luis",d:"Tolima",z:"municipal"},
{n:"San Luis de Gaceno",d:"Boyacá",z:"municipal"},
{n:"San Luis de Palenque",d:"Casanare",z:"municipal"},
{n:"San Marcos",d:"Sucre",z:"municipal"},
{n:"San Martín",d:"Cesar",z:"municipal"},
{n:"San Martín",d:"Meta",z:"municipal"},
{n:"San Martín de Loba",d:"Bolívar",z:"municipal"},
{n:"San Mateo",d:"Boyacá",z:"municipal"},
{n:"San Miguel",d:"Putumayo",z:"municipal"},
{n:"San Miguel",d:"Santander",z:"municipal"},
{n:"San Miguel de Sema",d:"Boyacá",z:"municipal"},
{n:"San Onofre",d:"Sucre",z:"municipal"},
{n:"San Pablo",d:"Bolívar",z:"municipal"},
{n:"San Pablo",d:"Nariño",z:"municipal"},
{n:"San Pablo de Borbur",d:"Boyacá",z:"municipal"},
{n:"San Pedro",d:"Sucre",z:"municipal"},
{n:"San Pedro",d:"Valle del Cauca",z:"municipal"},
{n:"San Pedro de Cartago",d:"Nariño",z:"municipal"},
{n:"San Pedro de los Milagros",d:"Antioquia",z:"regional"},
{n:"San Pedro de Urabá",d:"Antioquia",z:"regional"},
{n:"San Pelayo",d:"Córdoba",z:"municipal"},
{n:"San Rafael",d:"Antioquia",z:"regional"},
{n:"San Roque",d:"Antioquia",z:"regional"},
{n:"San Sebastián",d:"Cauca",z:"municipal"},
{n:"San Sebastián de Buenavista",d:"Magdalena",z:"municipal"},
{n:"San Vicente",d:"Antioquia",z:"regional"},
{n:"San Vicente de Chucurí",d:"Santander",z:"municipal"},
{n:"San Vicente del Caguán",d:"Caquetá",z:"municipal"},
{n:"San Zenón",d:"Magdalena",z:"municipal"},
{n:"Sandoná",d:"Nariño",z:"municipal"},
{n:"Santa Ana",d:"Magdalena",z:"municipal"},
{n:"Santa Bárbara",d:"Antioquia",z:"regional"},
{n:"Santa Bárbara",d:"Nariño",z:"municipal"},
{n:"Santa Bárbara",d:"Santander",z:"municipal"},
{n:"Santa Bárbara de Pinto",d:"Magdalena",z:"municipal"},
{n:"Santa Catalina",d:"Bolívar",z:"municipal"},
{n:"Santa Fe de Antioquia",d:"Antioquia",z:"regional"},
{n:"Santa Helena del Opón",d:"Santander",z:"municipal"},
{n:"Santa Isabel",d:"Tolima",z:"municipal"},
{n:"Santa Lucía",d:"Atlántico",z:"municipal"},
{n:"Santa María",d:"Boyacá",z:"municipal"},
{n:"Santa María",d:"Huila",z:"municipal"},
{n:"Santa Marta",d:"Magdalena",z:"metropolitano"},
{n:"Santa Rosa",d:"Bolívar",z:"municipal"},
{n:"Santa Rosa",d:"Cauca",z:"municipal"},
{n:"Santa Rosa de Cabal",d:"Risaralda",z:"regional"},
{n:"Santa Rosa de Osos",d:"Antioquia",z:"regional"},
{n:"Santa Rosa de Viterbo",d:"Boyacá",z:"municipal"},
{n:"Santa Rosa del Sur",d:"Bolívar",z:"municipal"},
{n:"Santa Rosalía",d:"Vichada",z:"municipal"},
{n:"Santa Sofía",d:"Boyacá",z:"municipal"},
{n:"Santacruz",d:"Nariño",z:"municipal"},
{n:"Santana",d:"Boyacá",z:"municipal"},
{n:"Santander de Quilichao",d:"Cauca",z:"municipal"},
{n:"Santiago",d:"Norte de Santander",z:"municipal"},
{n:"Santiago",d:"Putumayo",z:"municipal"},
{n:"Santo Domingo",d:"Antioquia",z:"regional"},
{n:"Santo Domingo de Silos",d:"Norte de Santander",z:"municipal"},
{n:"Santo Tomás",d:"Atlántico",z:"municipal"},
{n:"Santuario",d:"Risaralda",z:"regional"},
{n:"Sapuyes",d:"Nariño",z:"municipal"},
{n:"Saravena",d:"Arauca",z:"municipal"},
{n:"Sardinata",d:"Norte de Santander",z:"municipal"},
{n:"Sasaima",d:"Cundinamarca",z:"municipal"},
{n:"Sativanorte",d:"Boyacá",z:"municipal"},
{n:"Sativasur",d:"Boyacá",z:"municipal"},
{n:"Segovia",d:"Antioquia",z:"regional"},
{n:"Sesquilé",d:"Cundinamarca",z:"municipal"},
{n:"Sevilla",d:"Valle del Cauca",z:"municipal"},
{n:"Siachoque",d:"Boyacá",z:"municipal"},
{n:"Sibaté",d:"Cundinamarca",z:"municipal"},
{n:"Sibundoy",d:"Putumayo",z:"municipal"},
{n:"Silvania",d:"Cundinamarca",z:"municipal"},
{n:"Silvia",d:"Cauca",z:"municipal"},
{n:"Simacota",d:"Santander",z:"municipal"},
{n:"Simijaca",d:"Cundinamarca",z:"municipal"},
{n:"Simití",d:"Bolívar",z:"municipal"},
{n:"Sincé",d:"Sucre",z:"municipal"},
{n:"Sincelejo",d:"Sucre",z:"metropolitano"},
{n:"Sipí",d:"Chocó",z:"municipal"},
{n:"Sitionuevo",d:"Magdalena",z:"municipal"},
{n:"Soacha",d:"Cundinamarca",z:"metropolitano"},
{n:"Soatá",d:"Boyacá",z:"municipal"},
{n:"Socha",d:"Boyacá",z:"municipal"},
{n:"Socotá",d:"Boyacá",z:"municipal"},
{n:"Sogamoso",d:"Boyacá",z:"municipal"},
{n:"Solano",d:"Caquetá",z:"municipal"},
{n:"Soledad",d:"Atlántico",z:"metropolitano"},
{n:"Solita",d:"Caquetá",z:"municipal"},
{n:"Somondoco",d:"Boyacá",z:"municipal"},
{n:"Sonsón",d:"Antioquia",z:"regional"},
{n:"Sopetrán",d:"Antioquia",z:"regional"},
{n:"Soplaviento",d:"Bolívar",z:"municipal"},
{n:"Sopó",d:"Cundinamarca",z:"municipal"},
{n:"Sora",d:"Boyacá",z:"municipal"},
{n:"Soracá",d:"Boyacá",z:"municipal"},
{n:"Sotaquirá",d:"Boyacá",z:"municipal"},
{n:"Sotará",d:"Cauca",z:"municipal"},
{n:"Suaita",d:"Santander",z:"municipal"},
{n:"Suán",d:"Atlántico",z:"municipal"},
{n:"Suárez",d:"Cauca",z:"municipal"},
{n:"Suárez",d:"Tolima",z:"municipal"},
{n:"Suaza",d:"Huila",z:"municipal"},
{n:"Subachoque",d:"Cundinamarca",z:"municipal"},
{n:"Sucre",d:"Cauca",z:"municipal"},
{n:"Sucre",d:"Santander",z:"municipal"},
{n:"Sucre",d:"Sucre",z:"municipal"},
{n:"Suesca",d:"Cundinamarca",z:"municipal"},
{n:"Supatá",d:"Cundinamarca",z:"municipal"},
{n:"Supía",d:"Caldas",z:"regional"},
{n:"Suratá",d:"Santander",z:"municipal"},
{n:"Susa",d:"Cundinamarca",z:"municipal"},
{n:"Susacón",d:"Boyacá",z:"municipal"},
{n:"Sutamarchán",d:"Boyacá",z:"municipal"},
{n:"Sutatausa",d:"Cundinamarca",z:"municipal"},
{n:"Sutatenza",d:"Boyacá",z:"municipal"},
{n:"Tabio",d:"Cundinamarca",z:"municipal"},
{n:"Tadó",d:"Chocó",z:"municipal"},
{n:"Talaigua Nuevo",d:"Bolívar",z:"municipal"},
{n:"Tamalameque",d:"Cesar",z:"municipal"},
{n:"Támara",d:"Casanare",z:"municipal"},
{n:"Tame",d:"Arauca",z:"municipal"},
{n:"Támesis",d:"Antioquia",z:"regional"},
{n:"Taminango",d:"Nariño",z:"municipal"},
{n:"Tangua",d:"Nariño",z:"municipal"},
{n:"Taraira",d:"Vaupés",z:"municipal"},
{n:"Tarazá",d:"Antioquia",z:"regional"},
{n:"Tarqui",d:"Huila",z:"municipal"},
{n:"Tarso",d:"Antioquia",z:"regional"},
{n:"Tasco",d:"Boyacá",z:"municipal"},
{n:"Tauramena",d:"Casanare",z:"municipal"},
{n:"Tausa",d:"Cundinamarca",z:"municipal"},
{n:"Tello",d:"Huila",z:"municipal"},
{n:"Tena",d:"Cundinamarca",z:"municipal"},
{n:"Tenerife",d:"Magdalena",z:"municipal"},
{n:"Tenjo",d:"Cundinamarca",z:"municipal"},
{n:"Tenza",d:"Boyacá",z:"municipal"},
{n:"Teorama",d:"Norte de Santander",z:"municipal"},
{n:"Teruel",d:"Huila",z:"municipal"},
{n:"Tesalia",d:"Huila",z:"municipal"},
{n:"Tibacuy",d:"Cundinamarca",z:"municipal"},
{n:"Tibaná",d:"Boyacá",z:"municipal"},
{n:"Tibasosa",d:"Boyacá",z:"municipal"},
{n:"Tibirita",d:"Cundinamarca",z:"municipal"},
{n:"Tibú",d:"Norte de Santander",z:"municipal"},
{n:"Tierralta",d:"Córdoba",z:"municipal"},
{n:"Timaná",d:"Huila",z:"municipal"},
{n:"Timbío",d:"Cauca",z:"municipal"},
{n:"Timbiquí",d:"Cauca",z:"municipal"},
{n:"Tinjacá",d:"Boyacá",z:"municipal"},
{n:"Tipacoque",d:"Boyacá",z:"municipal"},
{n:"Tiquisio",d:"Bolívar",z:"municipal"},
{n:"Titiribí",d:"Antioquia",z:"regional"},
{n:"Toca",d:"Boyacá",z:"municipal"},
{n:"Tocaima",d:"Cundinamarca",z:"municipal"},
{n:"Tocancipá",d:"Cundinamarca",z:"municipal"},
{n:"Togüí",d:"Boyacá",z:"municipal"},
{n:"Toledo",d:"Antioquia",z:"regional"},
{n:"Toledo",d:"Norte de Santander",z:"municipal"},
{n:"Tolú",d:"Sucre",z:"municipal"},
{n:"Tolú Viejo",d:"Sucre",z:"municipal"},
{n:"Tona",d:"Santander",z:"municipal"},
{n:"Tópaga",d:"Boyacá",z:"municipal"},
{n:"Topaipí",d:"Cundinamarca",z:"municipal"},
{n:"Toribío",d:"Cauca",z:"municipal"},
{n:"Toro",d:"Valle del Cauca",z:"municipal"},
{n:"Tota",d:"Boyacá",z:"municipal"},
{n:"Totoró",d:"Cauca",z:"municipal"},
{n:"Trinidad",d:"Casanare",z:"municipal"},
{n:"Trujillo",d:"Valle del Cauca",z:"municipal"},
{n:"Tubará",d:"Atlántico",z:"municipal"},
{n:"Tuchín",d:"Córdoba",z:"municipal"},
{n:"Tuluá",d:"Valle del Cauca",z:"municipal"},
{n:"Tumaco",d:"Nariño",z:"municipal"},
{n:"Tunja",d:"Boyacá",z:"metropolitano"},
{n:"Tununguá",d:"Boyacá",z:"municipal"},
{n:"Túquerres",d:"Nariño",z:"municipal"},
{n:"Turbaco",d:"Bolívar",z:"municipal"},
{n:"Turbaná",d:"Bolívar",z:"municipal"},
{n:"Turbo",d:"Antioquia",z:"regional"},
{n:"Turmequé",d:"Boyacá",z:"municipal"},
{n:"Tuta",d:"Boyacá",z:"municipal"},
{n:"Tutazá",d:"Boyacá",z:"municipal"},
{n:"Ubalá",d:"Cundinamarca",z:"municipal"},
{n:"Ubaque",d:"Cundinamarca",z:"municipal"},
{n:"Ubaté",d:"Cundinamarca",z:"municipal"},
{n:"Ulloa",d:"Valle del Cauca",z:"municipal"},
{n:"Úmbita",d:"Boyacá",z:"municipal"},
{n:"Une",d:"Cundinamarca",z:"municipal"},
{n:"Unguía",d:"Chocó",z:"municipal"},
{n:"Unión Panamericana",d:"Chocó",z:"municipal"},
{n:"Uramita",d:"Antioquia",z:"regional"},
{n:"Uribia",d:"La Guajira",z:"municipal"},
{n:"Urrao",d:"Antioquia",z:"regional"},
{n:"Urumita",d:"La Guajira",z:"municipal"},
{n:"Usiacurí",d:"Atlántico",z:"municipal"},
{n:"Útica",d:"Cundinamarca",z:"municipal"},
{n:"Valdivia",d:"Antioquia",z:"regional"},
{n:"Valencia",d:"Córdoba",z:"municipal"},
{n:"Valle de San José",d:"Santander",z:"municipal"},
{n:"Valle de San Juan",d:"Tolima",z:"municipal"},
{n:"Valle del Guamuez",d:"Putumayo",z:"municipal"},
{n:"Valledupar",d:"Cesar",z:"metropolitano"},
{n:"Valparaíso",d:"Antioquia",z:"regional"},
{n:"Valparaíso",d:"Caquetá",z:"municipal"},
{n:"Vegachí",d:"Antioquia",z:"regional"},
{n:"Vélez",d:"Santander",z:"municipal"},
{n:"Venadillo",d:"Tolima",z:"municipal"},
{n:"Venecia",d:"Antioquia",z:"regional"},
{n:"Venecia",d:"Cundinamarca",z:"municipal"},
{n:"Ventaquemada",d:"Boyacá",z:"municipal"},
{n:"Vergara",d:"Cundinamarca",z:"municipal"},
{n:"Versalles",d:"Valle del Cauca",z:"municipal"},
{n:"Vetas",d:"Santander",z:"municipal"},
{n:"Vianí",d:"Cundinamarca",z:"municipal"},
{n:"Victoria",d:"Caldas",z:"regional"},
{n:"Vigía del Fuerte",d:"Antioquia",z:"regional"},
{n:"Vijes",d:"Valle del Cauca",z:"municipal"},
{n:"Villa Caro",d:"Norte de Santander",z:"municipal"},
{n:"Villa de Leyva",d:"Boyacá",z:"municipal"},
{n:"Villa del Rosario",d:"Norte de Santander",z:"municipal"},
{n:"Villa Rica",d:"Cauca",z:"municipal"},
{n:"Villagarzón",d:"Putumayo",z:"municipal"},
{n:"Villagómez",d:"Cundinamarca",z:"municipal"},
{n:"Villahermosa",d:"Tolima",z:"municipal"},
{n:"Villamaría",d:"Caldas",z:"regional"},
{n:"Villanueva",d:"Bolívar",z:"municipal"},
{n:"Villanueva",d:"Casanare",z:"municipal"},
{n:"Villanueva",d:"La Guajira",z:"municipal"},
{n:"Villanueva",d:"Santander",z:"municipal"},
{n:"Villapinzón",d:"Cundinamarca",z:"municipal"},
{n:"Villarrica",d:"Tolima",z:"municipal"},
{n:"Villavicencio",d:"Meta",z:"metropolitano"},
{n:"Villavieja",d:"Huila",z:"municipal"},
{n:"Villeta",d:"Cundinamarca",z:"municipal"},
{n:"Viotá",d:"Cundinamarca",z:"municipal"},
{n:"Viracachá",d:"Boyacá",z:"municipal"},
{n:"Vista Hermosa",d:"Meta",z:"municipal"},
{n:"Viterbo",d:"Caldas",z:"regional"},
{n:"Yacopí",d:"Cundinamarca",z:"municipal"},
{n:"Yacuanquer",d:"Nariño",z:"municipal"},
{n:"Yaguará",d:"Huila",z:"municipal"},
{n:"Yalí",d:"Antioquia",z:"regional"},
{n:"Yarumal",d:"Antioquia",z:"regional"},
{n:"Yolombó",d:"Antioquia",z:"regional"},
{n:"Yondó",d:"Antioquia",z:"regional"},
{n:"Yopal",d:"Casanare",z:"metropolitano"},
{n:"Yotoco",d:"Valle del Cauca",z:"municipal"},
{n:"Yumbo",d:"Valle del Cauca",z:"metropolitano"},
{n:"Zambrano",d:"Bolívar",z:"municipal"},
{n:"Zapatoca",d:"Santander",z:"municipal"},
{n:"Zapayán",d:"Magdalena",z:"municipal"},
{n:"Zaragoza",d:"Antioquia",z:"regional"},
{n:"Zarzal",d:"Valle del Cauca",z:"municipal"},
{n:"Zetaquira",d:"Boyacá",z:"municipal"},
{n:"Zipacón",d:"Cundinamarca",z:"municipal"},
{n:"Zipaquirá",d:"Cundinamarca",z:"municipal"},
{n:"Zona Bananera",d:"Magdalena",z:"municipal"}
];
